name: 'Multiple Codeowners Action'
description: 'Combines multiple CODEOWNERS files into a single one at a specified location'
author: 'cbrgm'

inputs:
  output:
    description: 'Path where the combined CODEOWNERS file will be written, relative to the repository root'
    required: false
    default: '.github/CODEOWNERS'
  repository:
    description: 'Path to the repository root, if different from the default GitHub Actions workspace'
    required: false
    default: '.'
  dry-run:
    description: 'Perform a dry run without actually writing the combined CODEOWNERS file'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/cbrgm/multiple-codeowners-action:v1'
  args:
    - --output
    - ${{ inputs.output }}
    - --repository
    - ${{ inputs.repository }}
    - --dry-run=${{ inputs.dry-run }}

branding:
  icon: 'git-pull-request'
  color: 'blue'

