FROM amd64/alpine:3.19 AS build
RUN apk add --no-cache ca-certificates

FROM scratch

ENTRYPOINT ["/usr/bin/multiple-codeowners-action"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY bin/multiple-codeowners-action /usr/bin/multiple-codeowners-action
